[package]
name = "scanner"
version = "0.1.0"
edition = "2021"

[dependencies]
text_io = "0.1.12"
entropy-lib = "1.0.2"
bin_file = "0.1.1"
crc = "3.2.1"
regex = "1.11.0"
shannon-entropy = "0.2"
flate2 = "1.0" 
zip = "0.5"  


